### ISSUE TITLE
rust查看可编译架构

### ISSUE THREAD

**Issue by Triment** [Triment/blog#26]
cargo.toml
```toml
[build]
target="x86_64-pc-windows-msvc"
```
cmd
```cmd
rustc --print target-list
```
[参考](https://doc.rust-lang.org/cargo/commands/cargo-build.html)
